"""Seed master data sourced from data/COA-7-GRUP-9265c7.xlsx."""

# Chart of Accounts BUMDES sesuai struktur terbaru (7 grup: BUMDES, UU01-UU06)
# Single source of truth for account validation and import templates.
# Keep these identifiers stable: reporting logic uses the subcategory values directly.
VALID_ACCOUNT_CATEGORIES = {
    'aset': ('kas_bank', 'aset_lancar', 'aset_tetap'),
    'beban': ('beban_administrasi', 'beban_operasional', 'beban_lain_lain'),
    'ekuitas': ('modal_desa', 'modal_masyarakat', 'bagi_hasil_desa', 'bagi_hasil_masyarakat', 'saldo_laba', 'ikhtisar_laba_rugi'),
    'kewajiban': ('kewajiban_jangka_pendek',),
    'pendapatan': ('pendapatan_operasional', 'pendapatan_non_operasional'),
}

# Compatibility name used by account template/import code.
VALID_CATEGORIES = VALID_ACCOUNT_CATEGORIES

# code, name, category, subcategory, normal_balance, group
# Subcategories: kas_bank, aset_lancar, aset_tetap, kewajiban_jangka_pendek,
#                modal_desa, modal_masyarakat, bagi_hasil_desa, bagi_hasil_masyarakat, saldo_laba, ikhtisar_laba_rugi,
#                pendapatan_operasional, pendapatan_non_operasional,
#                beban_administrasi, beban_operasional, beban_lain_lain
CHART_OF_ACCOUNTS = [
    ('1.1.01.01', 'Kas/Bank - BUMDES (Pusat)', 'aset', 'kas_bank', 'debit', 'BUMDES'),
    ('1.1.01.02', 'Kas di Bank BJB', 'aset', 'kas_bank', 'debit', 'BUMDES'),
    ('1.1.01.03', 'Kas di Bank OCBC', 'aset', 'kas_bank', 'debit', 'BUMDES'),
    ('1.1.03.01', 'Piutang Usaha', 'aset', 'aset_lancar', 'debit', 'BUMDES'),
    ('1.2.01.01', 'Penyertaan Modal Kerja', 'aset', 'aset_lancar', 'debit', 'BUMDES'),
    ('1.3.01.01', 'Tanah', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.3.02.01', 'Kendaraan', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.3.03.01', 'Peralatan, Mesin, dan Inventaris Kantor', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.3.04.01', 'Meubelair', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.3.05.01', 'Gedung dan Bangunan', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.3.06.01', 'Konstruksi dalam Pengerjaan', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.3.07.01', 'Akumulasi Penyusutan Kendaraan', 'aset', 'aset_tetap', 'kredit', 'BUMDES'),
    ('1.3.07.02', 'Akumulasi Penyusutan Peralatan, Mesin, dan Inventaris Kantor', 'aset', 'aset_tetap', 'kredit', 'BUMDES'),
    ('1.3.07.03', 'Akumulasi Penyusutan Meubelair', 'aset', 'aset_tetap', 'kredit', 'BUMDES'),
    ('1.3.07.04', 'Akumulasi Penyusutan Gedung dan Bangunan', 'aset', 'aset_tetap', 'kredit', 'BUMDES'),
    ('1.4.01.01', 'Aset Tetap Biologis', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.5.01.01', 'Aset Tetap Tak Berwujud', 'aset', 'aset_tetap', 'debit', 'BUMDES'),
    ('1.5.02.01', 'Amortisasi Aset takberwujud', 'aset', 'aset_tetap', 'kredit', 'BUMDES'),
    ('2.1.01.01', 'Utang Usaha', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'BUMDES'),
    ('2.1.03.01', 'Utang Bagi Hasil PADes (30%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'BUMDES'),
    ('2.1.03.02', 'Utang Bagi Hasil Penasihat (7%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'BUMDES'),
    ('2.1.03.03', 'Utang Bagi Hasil Pengawas (5%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'BUMDES'),
    ('2.1.03.04', 'Utang Bagi Hasil Pengurus (35%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'BUMDES'),
    ('2.1.03.05', 'Utang Bagi Hasil Dana Sosial (5%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'BUMDES'),
    ('3.1.01.01', 'Penyertaan Modal Desa', 'ekuitas', 'modal_desa', 'kredit', 'BUMDES'),
    ('3.1.02.01', 'Penyertaan Modal Masyarakat', 'ekuitas', 'modal_masyarakat', 'kredit', 'BUMDES'),
    ('3.2.01.01', 'Bagi Hasil Penyertaan Modal Desa', 'ekuitas', 'bagi_hasil_desa', 'debit', 'BUMDES'),
    ('3.2.02.01', 'Bagi Hasil Penyertaan Modal Masyarakat', 'ekuitas', 'bagi_hasil_masyarakat', 'debit', 'BUMDES'),
    ('3.3.01.01', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'kredit', 'BUMDES'),
    ('3.9.01.01', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'kredit', 'BUMDES'),
    ('4.1.01.01', 'Pendapatan Usaha', 'pendapatan', 'pendapatan_operasional', 'kredit', 'BUMDES'),
    ('4.2.01.01', 'Pendapatan Lain-lain', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'BUMDES'),
    ('4.2.01.02', 'Bunga Bank', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'BUMDES'),
    ('6.1.01.01', 'Beban Administrasi Umum', 'beban', 'beban_administrasi', 'debit', 'BUMDES'),
    ('6.1.99.01', 'Beban Administrasi Lainnya', 'beban', 'beban_administrasi', 'debit', 'BUMDES'),
    ('6.2.01.01', 'Beban Operasional Umum', 'beban', 'beban_operasional', 'debit', 'BUMDES'),
    ('6.2.99.01', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'debit', 'BUMDES'),
    ('6.3.01.01', 'Admin Bank', 'beban', 'beban_lain_lain', 'debit', 'BUMDES'),
    ('6.3.01.02', 'Pajak Bunga Bank', 'beban', 'beban_lain_lain', 'debit', 'BUMDES'),
    ('1.1.01.11', 'Kas/Bank - UU01', 'aset', 'kas_bank', 'debit', 'UU01'),
    ('1.1.03.11', 'Piutang Usaha', 'aset', 'aset_lancar', 'debit', 'UU01'),
    ('2.1.01.11', 'Utang Usaha', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU01'),
    ('2.1.03.11', 'Utang Bagi Hasil BUMDES (70%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU01'),
    ('2.1.03.12', 'Utang Bagi Hasil Pengelola (30%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU01'),
    ('3.1.01.11', 'Penyertaan Modal BUMDES', 'ekuitas', 'modal_desa', 'kredit', 'UU01'),
    ('3.1.02.11', 'Penyertaan Modal Lainnya', 'ekuitas', 'modal_masyarakat', 'kredit', 'UU01'),
    ('3.2.01.11', 'Bagi Hasil Penyertaan Modal BUMDES', 'ekuitas', 'bagi_hasil_desa', 'debit', 'UU01'),
    ('3.2.02.11', 'Bagi Hasil Penyertaan Modal Lainnya', 'ekuitas', 'bagi_hasil_masyarakat', 'debit', 'UU01'),
    ('3.3.01.11', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'kredit', 'UU01'),
    ('3.9.01.11', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'kredit', 'UU01'),
    ('4.1.01.11', 'Pendapatan Usaha', 'pendapatan', 'pendapatan_operasional', 'kredit', 'UU01'),
    ('4.2.01.11', 'Pendapatan Lain-lain', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'UU01'),
    ('6.1.01.11', 'Beban Administrasi Umum', 'beban', 'beban_administrasi', 'debit', 'UU01'),
    ('6.1.99.11', 'Beban Administrasi Lainnya', 'beban', 'beban_administrasi', 'debit', 'UU01'),
    ('6.2.01.11', 'Beban Operasional Umum', 'beban', 'beban_operasional', 'debit', 'UU01'),
    ('6.2.99.11', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'debit', 'UU01'),
    ('1.1.01.12', 'Kas/Bank - UU02', 'aset', 'kas_bank', 'debit', 'UU02'),
    ('1.1.03.12', 'Piutang Usaha', 'aset', 'aset_lancar', 'debit', 'UU02'),
    ('2.1.01.12', 'Utang Usaha', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU02'),
    ('2.1.03.21', 'Utang Bagi Hasil BUMDES (70%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU02'),
    ('2.1.03.22', 'Utang Bagi Hasil Pengelola (30%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU02'),
    ('3.1.01.21', 'Penyertaan Modal BUMDES', 'ekuitas', 'modal_desa', 'kredit', 'UU02'),
    ('3.1.02.21', 'Penyertaan Modal Lainnya', 'ekuitas', 'modal_masyarakat', 'kredit', 'UU02'),
    ('3.2.01.21', 'Bagi Hasil Penyertaan Modal BUMDES', 'ekuitas', 'bagi_hasil_desa', 'debit', 'UU02'),
    ('3.2.02.21', 'Bagi Hasil Penyertaan Modal Lainnya', 'ekuitas', 'bagi_hasil_masyarakat', 'debit', 'UU02'),
    ('3.3.01.12', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'kredit', 'UU02'),
    ('3.9.01.12', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'kredit', 'UU02'),
    ('4.1.01.12', 'Pendapatan Usaha', 'pendapatan', 'pendapatan_operasional', 'kredit', 'UU02'),
    ('4.2.01.12', 'Pendapatan Lain-lain', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'UU02'),
    ('6.1.01.21', 'Beban Administrasi Umum', 'beban', 'beban_administrasi', 'debit', 'UU02'),
    ('6.1.99.21', 'Beban Administrasi Lainnya', 'beban', 'beban_administrasi', 'debit', 'UU02'),
    ('6.2.01.21', 'Beban Operasional Umum', 'beban', 'beban_operasional', 'debit', 'UU02'),
    ('6.2.99.21', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'debit', 'UU02'),
    ('1.1.01.13', 'Kas/Bank - UU03', 'aset', 'kas_bank', 'debit', 'UU03'),
    ('1.1.03.13', 'Piutang Usaha', 'aset', 'aset_lancar', 'debit', 'UU03'),
    ('2.1.01.13', 'Utang Usaha', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU03'),
    ('2.1.03.31', 'Utang Bagi Hasil BUMDES (70%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU03'),
    ('2.1.03.32', 'Utang Bagi Hasil Pengelola (30%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU03'),
    ('3.1.01.31', 'Penyertaan Modal BUMDES', 'ekuitas', 'modal_desa', 'kredit', 'UU03'),
    ('3.1.02.31', 'Penyertaan Modal Lainnya', 'ekuitas', 'modal_masyarakat', 'kredit', 'UU03'),
    ('3.2.01.31', 'Bagi Hasil Penyertaan Modal BUMDES', 'ekuitas', 'bagi_hasil_desa', 'debit', 'UU03'),
    ('3.2.02.31', 'Bagi Hasil Penyertaan Modal Lainnya', 'ekuitas', 'bagi_hasil_masyarakat', 'debit', 'UU03'),
    ('3.3.01.13', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'kredit', 'UU03'),
    ('3.9.01.13', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'kredit', 'UU03'),
    ('4.1.01.13', 'Pendapatan Usaha', 'pendapatan', 'pendapatan_operasional', 'kredit', 'UU03'),
    ('4.2.01.13', 'Pendapatan Lain-lain', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'UU03'),
    ('6.1.01.31', 'Beban Administrasi Umum', 'beban', 'beban_administrasi', 'debit', 'UU03'),
    ('6.1.99.31', 'Beban Administrasi Lainnya', 'beban', 'beban_administrasi', 'debit', 'UU03'),
    ('6.2.01.31', 'Beban Operasional Umum', 'beban', 'beban_operasional', 'debit', 'UU03'),
    ('6.2.99.31', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'debit', 'UU03'),
    ('1.1.01.14', 'Kas/Bank - UU04', 'aset', 'kas_bank', 'debit', 'UU04'),
    ('1.1.03.14', 'Piutang Usaha', 'aset', 'aset_lancar', 'debit', 'UU04'),
    ('1.2.01.14', 'Penyertaan Modal Kerja', 'aset', 'aset_lancar', 'debit', 'UU04'),
    ('2.1.01.14', 'Utang Usaha', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU04'),
    ('2.1.03.41', 'Utang Bagi Hasil BUMDES (70%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU04'),
    ('2.1.03.42', 'Utang Bagi Hasil Pengelola (30%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU04'),
    ('3.1.01.41', 'Penyertaan Modal BUMDES', 'ekuitas', 'modal_desa', 'kredit', 'UU04'),
    ('3.1.02.41', 'Penyertaan Modal Lainnya', 'ekuitas', 'modal_masyarakat', 'kredit', 'UU04'),
    ('3.2.01.41', 'Bagi Hasil Penyertaan Modal BUMDES', 'ekuitas', 'bagi_hasil_desa', 'debit', 'UU04'),
    ('3.2.02.41', 'Bagi Hasil Penyertaan Modal Lainnya', 'ekuitas', 'bagi_hasil_masyarakat', 'debit', 'UU04'),
    ('3.3.01.14', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'kredit', 'UU04'),
    ('3.9.01.14', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'kredit', 'UU04'),
    ('4.1.01.14', 'Pendapatan Usaha', 'pendapatan', 'pendapatan_operasional', 'kredit', 'UU04'),
    ('4.2.01.14', 'Pendapatan Lain-lain', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'UU04'),
    ('6.1.01.41', 'Beban Administrasi Umum', 'beban', 'beban_administrasi', 'debit', 'UU04'),
    ('6.1.99.41', 'Beban Administrasi Lainnya', 'beban', 'beban_administrasi', 'debit', 'UU04'),
    ('6.2.01.41', 'Beban Operasional Umum', 'beban', 'beban_operasional', 'debit', 'UU04'),
    ('6.2.99.41', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'debit', 'UU04'),
    ('1.1.01.15', 'Kas/Bank - UU05', 'aset', 'kas_bank', 'debit', 'UU05'),
    ('1.1.03.15', 'Piutang Usaha', 'aset', 'aset_lancar', 'debit', 'UU05'),
    ('2.1.01.15', 'Utang Usaha', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU05'),
    ('2.1.03.51', 'Utang Bagi Hasil BUMDES (70%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU05'),
    ('2.1.03.52', 'Utang Bagi Hasil Pengelola (30%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU05'),
    ('3.1.01.51', 'Penyertaan Modal BUMDES', 'ekuitas', 'modal_desa', 'kredit', 'UU05'),
    ('3.1.02.51', 'Penyertaan Modal Lainnya', 'ekuitas', 'modal_masyarakat', 'kredit', 'UU05'),
    ('3.2.01.51', 'Bagi Hasil Penyertaan Modal BUMDES', 'ekuitas', 'bagi_hasil_desa', 'debit', 'UU05'),
    ('3.2.02.51', 'Bagi Hasil Penyertaan Modal Lainnya', 'ekuitas', 'bagi_hasil_masyarakat', 'debit', 'UU05'),
    ('3.3.01.15', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'kredit', 'UU05'),
    ('3.9.01.15', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'kredit', 'UU05'),
    ('4.1.01.15', 'Pendapatan Usaha', 'pendapatan', 'pendapatan_operasional', 'kredit', 'UU05'),
    ('4.2.01.15', 'Pendapatan Lain-lain', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'UU05'),
    ('6.1.01.51', 'Beban Administrasi Umum', 'beban', 'beban_administrasi', 'debit', 'UU05'),
    ('6.1.99.51', 'Beban Administrasi Lainnya', 'beban', 'beban_administrasi', 'debit', 'UU05'),
    ('6.2.01.51', 'Beban Operasional Umum', 'beban', 'beban_operasional', 'debit', 'UU05'),
    ('6.2.99.51', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'debit', 'UU05'),
    ('1.1.01.16', 'Kas/Bank - UU06', 'aset', 'kas_bank', 'debit', 'UU06'),
    ('1.1.03.16', 'Piutang Usaha', 'aset', 'aset_lancar', 'debit', 'UU06'),
    ('2.1.01.16', 'Utang Usaha', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU06'),
    ('2.1.03.61', 'Utang Bagi Hasil BUMDES (70%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU06'),
    ('2.1.03.62', 'Utang Bagi Hasil Pengelola (30%)', 'kewajiban', 'kewajiban_jangka_pendek', 'kredit', 'UU06'),
    ('3.1.01.61', 'Penyertaan Modal BUMDES', 'ekuitas', 'modal_desa', 'kredit', 'UU06'),
    ('3.1.02.61', 'Penyertaan Modal Lainnya', 'ekuitas', 'modal_masyarakat', 'kredit', 'UU06'),
    ('3.2.01.61', 'Bagi Hasil Penyertaan Modal BUMDES', 'ekuitas', 'bagi_hasil_desa', 'debit', 'UU06'),
    ('3.2.02.61', 'Bagi Hasil Penyertaan Modal Lainnya', 'ekuitas', 'bagi_hasil_masyarakat', 'debit', 'UU06'),
    ('3.3.01.16', 'Saldo Laba', 'ekuitas', 'saldo_laba', 'kredit', 'UU06'),
    ('3.9.01.16', 'Ikhtisar Laba Rugi', 'ekuitas', 'ikhtisar_laba_rugi', 'kredit', 'UU06'),
    ('4.1.01.16', 'Pendapatan Usaha', 'pendapatan', 'pendapatan_operasional', 'kredit', 'UU06'),
    ('4.2.01.16', 'Pendapatan Lain-lain', 'pendapatan', 'pendapatan_non_operasional', 'kredit', 'UU06'),
    ('6.1.01.61', 'Beban Administrasi Umum', 'beban', 'beban_administrasi', 'debit', 'UU06'),
    ('6.1.99.61', 'Beban Administrasi Lainnya', 'beban', 'beban_administrasi', 'debit', 'UU06'),
    ('6.2.01.61', 'Beban Operasional Umum', 'beban', 'beban_operasional', 'debit', 'UU06'),
    ('6.2.99.61', 'Beban Operasional Lainnya', 'beban', 'beban_operasional', 'debit', 'UU06'),
]

EXAMPLE_ROWS_BUMDES = [row[:5] for row in CHART_OF_ACCOUNTS if row[5] == "BUMDES"]
EXAMPLE_ROWS_UNIT = {
    group: [row[:5] for row in CHART_OF_ACCOUNTS if row[5] == group]
    for group in ("UU01", "UU02", "UU03", "UU04", "UU05", "UU06")
}

UNIT_USAHA_SEED = [
    ('UU01', 'Pembibitan Domba Garut',
     'Kerjasama dengan ~15 mitra peternak domba di desa. Pengelola monitoring bulanan.',
     'Anakan dijual: 30% mitra, 70% BUMDES. Akumulasi 70% dikurangi op-cost, sisa dibagi 30% pengelola / 70% BUMDES.'),
    ('UU02', 'Peternakan Ikan Air Tawar Sistem Bioflok',
     'Kerjasama dengan ~24 mitra peternak ikan air tawar sistem bioflok.',
     'Mitra setor Rp3.000/kg ikan panen. Akumulasi dikurangi op-cost, sisa dibagi 30% pengelola / 70% BUMDES.'),
    ('UU03', 'Sewa Kendaraan Angkutan Barang',
     'Antar barang dari penjual online (afiliasi) dan pihak lain di lingkup Kec. Pangandaran.',
     'Uang jasa dikurangi op-cost BBM, sisa dibagi 30% pengelola / 70% BUMDES.'),
    ('UU04', 'Karya Raharja Sinergi Digital (KRSD)',
     'Kerjasama mitra usaha dan pengelolaan modal kerja digital.',
     'Mitra dititipi modal kerja, imbal hasil dikelola sesuai ketentuan BUMDES.'),
    ('UU05', 'Toko Offline BUMDES',
     'Menyediakan produk untuk masyarakat dan penjual online.',
     'Laba bersih dikurangi op-cost, sisa dibagi 30% pengelola / 70% BUMDES.'),
    ('UU06', 'Toko Online BUMDES',
     'Kanal digital: Shopee, Tokopedia, TikTokShop, Lazada, Blibli.',
     'Laba bersih dikurangi op-cost, sisa dibagi 30% pengelola / 70% BUMDES.'),
]
